apiVersion: v2
appVersion: 'gateway-api: v1.4.1, gateway-api-inference-extension: v1.3.0'
name: gateway-api-crds
description: App to install Gateway API CRDs to Giantswarm Clusters
home: https://github.com/giantswarm/gateway-api-crds-app
icon: https://s.giantswarm.io/app-icons/gateway-api/1/light.svg
sources:
  - https://github.com/kubernetes-sigs/gateway-api
  - https://github.com/kubernetes-sigs/gateway-api-inference-extension
version: 1.7.0
annotations:
  io.giantswarm.application.team: cabbage
  io.giantswarm.application.audience: "all"
kubeVersion: ">=1.25.0-0"
